branches:
    only:
        - master

sudo: required

language: python

services:
    - docker

script:
    - docker build -t gitlab.pnnl.gov:4567/idream/visualization:$TRAVIS_BUILD_NUMBER .
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push gitlab.pnnl.gov:4567/idream/visualization:$TRAVIS_BUILD_NUMBER
