'''Viewer classes for the IDREAM data model.

This class takes one or more models and prepares the data
for visuzlization by a Bokeh application.

'''

# General Python imports.
import abc

# Data Science imports.

# Visualization / Bokeh imports.


# Local imports.
from .model import Model


class View(abc.ABC):
    '''A base class for viewing data.
    
    This is an abstract base class, and is not usefull to instanciate
    on its own.

    A view will be generated by information by a controller, will have
    data passed to it in the form of one or more Model classes.
   
    '''
    
    def __init__(self, key_dims, val_dims, *models):
        '''Basic Veiw initialization.
        
        Args:
            key_dims (tuple[str]): The key dimensions of the view. These
                are the values that will be assignable to the X-axis.
            val_dims (tuple[str]): The value dimensions of the view. Such
                values will be assignable to the Y-axis.
            *models (:obj:`Model`): Model(s) assigned to this visualization.
            
        '''
        pass
    
    @classmethod
    def from_single_node(cls):
        pass
    
    @classmethod
    def from_multiple_nodes(cls):
        pass
    
    
    

class NMR(View):
    '''NMR Viewer class. To be moved.'''
    def __init__(self, model):
        pass


class ConcentrationRatio(View):
    '''Ratio Viewer class. To be moved.'''
    def __init__(self, model):
        pass
